### ISSUE TITLE
SetReadDeadline 设置时间太短导致大文件未完成传输被断开连接

### ISSUE THREAD

**Issue by azio7** [XIU2/SNIProxy#15]
### 问题描述

使用时发现，浏览器访问网页中的部分较大的文件（例如：[https://www.youtube.com/s/desktop/536ed9a8/jsbin/desktop_polymer.vflset/desktop_polymer.js](https://www.youtube.com/s/desktop/536ed9a8/jsbin/desktop_polymer.vflset/desktop_polymer.js)）无法完成传输导致网页渲染失败
打印io.copy处的error得到以下日志
```
2024/09/11 18:12:44 连接来自: 127.0.0.1:37496
2024/09/11 18:12:44 转发目标: www.youtube.com:443
2024/09/11 18:12:46 ioReflector: writeto tcp 127.0.0.1:443->127.0.0.1:37496: readfrom tcp 192.168.10.3:52868->192.168.10.1:10086: i/o timeout
2024/09/11 18:12:46 [127.0.0.1:37496] -> [www.youtube.com:443] 310 bytes
2024/09/11 18:12:46 ioReflector: writeto tcp 192.168.10.3:52868->192.168.10.1:10086: readfrom tcp 127.0.0.1:443->127.0.0.1:37496: use of closed network connection
2024/09/11 18:12:46 [www.youtube.com:443] -> [127.0.0.1:37496] 951724 bytes
```
更换socks5库[https://github.com/txthinking/socks5](https://github.com/txthinking/socks5)仍未解决
通过修改 main.go 134行的超时时间可以解决该问题
		`c.SetReadDeadline(time.Now().Add(3000 * time.Millisecond)) // 改为3000`

```
2024/09/11 19:14:03 连接来自: 127.0.0.1:45498
2024/09/11 19:14:03 转发目标: www.youtube.com:443
2024/09/11 19:14:06 ioReflector: <nil>
2024/09/11 19:14:06 isToClient: false
2024/09/11 19:14:06 [127.0.0.1:45498] -> [www.youtube.com:443] 416 bytes
2024/09/11 19:14:06 ioReflector: readfrom tcp 127.0.0.1:443->127.0.0.1:45498: read tcp 192.168.10.3:33300->192.168.10.1:10086: use of closed network connection
2024/09/11 19:14:06 isToClient: true
2024/09/11 19:14:06 [www.youtube.com:443] -> [127.0.0.1:45498] 8666086 bytes
```
以上测试均使用socks代理

### 软件版本

v1.0.2 2d613e8ed2ab13cf48ee675add34cd17d9dea5f7

**Comment by XIU2** [comment]
这点我确实忽视了，这个时间限制不合理，本来我是想当成简单的超时时间，结果看来并不行，反而会影响到后续转发传输数据，你这样加大时间无法根本解决问题，当文件更大时还会出现该问题，我研究测试了一下，直接把这个去掉了，其他地方代码也适当调整了下，适配丢包的问题确实不合适在这里做（或者说以我的技术无法做到完美），那就干脆只用来处理握手消息分段的情况吧（重试次数也缩为 2 次就够了）。

更新试试吧。
