### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by hieixu** [XIU2/SNIProxy#17]
### 问题描述

通过代理运行sniproxy
每秒的请求次数超过100次， 程序刚开的时候，内存占用只有几十MB，随着慢慢上涨。
1个小时后，内存占用超过了1.5GiB

### 软件版本

v1.0.3

**Comment by XIU2** [comment]
所以我才不建议在正式的生产环境下不建议使用该软件，因为毛病比较多~

**Comment by hieixu** [comment]
我已经在生产环境用了，除了这个问题，同事们都是绝赞好评
目前我在docker内使用这个软件，限制了最大内存占用，超过设置的内存就重启，也就一两秒内不可用，影响不大。
如果能够修复，那是最好的

**Comment by XIU2** [comment]
主要是我的 Go 语言是临时自学，属于半吊子，目前的该项目也只是按照我自己的需求设计编写的，拼拼凑凑加上 GPT 和 Copilot 辅助才做出来的，这个项目相比我另一个 CloudflareST 会更底层一些（TCP / HTTP 方面知识偏多），对我来说还是比较勉强，所以我一开始就标注上了不建议在生产环境下使用。。。
特别是像这种内存泄漏类的问题，我还真没处理过。。。

你尝试降级到 v1.0.1 甚至 v1.0.0 试试看是否会好点，因为我 v1.0.2 折腾了新功能可能会增加内存使用率或影响回收率？不过我也不确定。。。

**Comment by hieixu** [comment]
v1.0.0 就有这个毛病，然后我升级到v1.0.3还是没改变

**Comment by XIU2** [comment]
有个热心网友提了个 PR #18 似乎修复了该问题，我这边简单测试没啥问题，所以希望你帮忙测试下，看**高负载下**内存泄漏问题是否修复。

我将这个 PR 的代码编译出来了几个 Window、Linux 版本（包括 amd64 arm 等架构），你试试吧（如果这几个都不是你要用的版本，可以跟我说，我再单独编译）

[windows+linux_beta.zip](https://github.com/user-attachments/files/17160375/windows%2Blinux_beta.zip)

**Comment by hieixu** [comment]
确定解决了我这边的内存泄漏问题
跑了10分钟，打了2万次请求，内存基本保持着10M左右

**Comment by XIU2** [comment]
如果你确定没有了内存泄漏问题，也没有遇到其他传输方面的问题，那我就 合并 并发布正式版本了。

**Comment by hieixu** [comment]
我这里的测试一切正常，内存泄漏问题也解决了

**Comment by XIU2** [comment]
已合并 并 正式发布 v1.0.4 版本：
https://github.com/XIU2/SNIProxy/releases/tag/v1.0.4
