### ISSUE TITLE
无法访问pixiv.net

### ISSUE THREAD

**Issue by QueenLoli** [XIU2/SNIProxy#2]
### 问题描述

```
# 监听端口
listen_addr: :443

# 可选：启用 Socks5 前置代理
#enable_socks5: true
# 可选：配置 Socks5 代理地址
#socks_addr: 127.0.0.1:40000

# 可选：允许所有域名（会忽略下面的 rules 列表）
allow_all_hosts: true

# 可选：仅允许指定域名
#rules:
#  - example.com
#  - b.example2.com
```

该设置下无法访问pixiv，显示www.pixiv.net 花了太长时间进行响应
dns使用的是阿里和腾讯的DOH

### 软件版本

v1.0.0

**Comment by XIU2** [comment]
`dns使用的是阿里和腾讯的DOH`

啥意思？你是在你本地电脑上运行的？还是服务器上？

**Comment by XIU2** [comment]
另外，现在而言，SNI Proxy 对过墙的作用并不大。
如果你是想在服务器上搭建一个 SNI Proxy，然后本地电脑将 Pixiv 域名 hosts 指向服务器的 IP 来过墙访问的话，劝你放弃。

因为现在一般都是 `DNS 污染 + SNI 阻断` 这种标配套餐了（只有一些早期被封或不太敏感的域名才会仅 DNS 污染），DNS 污染好解决，SNI 阻断的话是会阻止你访问服务器上的 SNI Proxy 服务的，因为墙和 SNI Proxy 一样，都是通过明文传输的 SNI 中的域名来判断的（不过一个是阻断/重置连接，另一个是转发流量）。

**Comment by QueenLoli** [comment]
是本地运行，我是想拿来过pixiv的sni阻断的。
单独跑sni proxy的话，GitHub还是可以正常访问

**Comment by XIU2** [comment]
SNIProxy 本质也算是一种端口转发（中转），但不同于端口转发只能指定一个固定的目标 IP，SNIProxy 可以通过 DNS 解析传入的域名来获得灵活的目标 IP。

因此你的要求无法实现，因为 SNI Proxy 会把你的所有流量转发至目标，包括明文的 SNI 信息。
